### ISSUE TITLE
Tikz visualization ToDo list

### ISSUE THREAD

**Issue by GiggleLiu** [QuEraComputing/UnitDiskMapping.jl#19]
TODOs:

* [ ] generate all figures (except the main one) used in the paper,
* [ ] Annotate text at left/right of a node,
* [ ] write a minimum version of documentation to describe the Kwargs.
* [ ] test curved connection (with controls),
* [ ] use this package in tensor visualization.
* [ ] Run latex build script.

_Originally posted by @GiggleLiu in https://github.com/Happy-Diode/UnitDiskMapping.jl/issues/18#issuecomment-993125308_
